"""ORM model registry.

Importing this package imports every model, which is what populates
``Base.metadata``. Alembic's ``env.py`` and the test fixtures both rely on that
side effect — a model that is never imported is silently absent from
autogenerated migrations.
"""

from app.db.base import Base
from app.db.models.document import Document
from app.db.models.enums import (
    ChunkType,
    DocumentRole,
    DocumentStatus,
    GroundingVerdict,
    Language,
    ParseStrategy,
    ProposalStatus,
    TenantPlan,
    UserRole,
    WorkspaceStatus,
)
from app.db.models.proposal import GeneratedProposal
from app.db.models.tenant import Tenant
from app.db.models.user import User
from app.db.models.workspace import Workspace

__all__ = [
    "Base",
    "ChunkType",
    "Document",
    "DocumentRole",
    "DocumentStatus",
    "GeneratedProposal",
    "GroundingVerdict",
    "Language",
    "ParseStrategy",
    "ProposalStatus",
    "Tenant",
    "TenantPlan",
    "User",
    "UserRole",
    "Workspace",
    "WorkspaceStatus",
]
