"""What the exported files actually contain.

Arabic layout is the part that cannot be checked by reading the code. Word and
a PDF renderer both accept a document with the glyphs right and the direction
wrong, and it looks fine until an evaluator opens it — so these tests read the
generated bytes back and assert on the markers that make the layout correct.
"""

from __future__ import annotations

import io
import zipfile
from datetime import UTC, datetime

import pytest
from app.db.models.enums import Language, ProposalStatus
from app.exports.compliance_matrix import build_compliance_matrix
from app.exports.models import ExportBundle, ExportRow
from app.exports.pdf import build_pdf, has_arabic_font
from app.exports.response_document import build_response_docx
from openpyxl import load_workbook

ARABIC_ANSWER = "نعم، نمتلك شهادة الأيزو 27001 سارية المفعول حتى عام 2027."
ENGLISH_ANSWER = "Yes, we hold a valid ISO 27001 certificate."


def _bundle(language: Language, *rows: ExportRow) -> ExportBundle:
    return ExportBundle(
        workspace_name="Ministry of Health 2026",
        tenant_name="Acme",
        language=language,
        rows=list(rows),
        generated_at=datetime(2026, 8, 18, 12, 0, tzinfo=UTC),
    )


def _row(**overrides) -> ExportRow:
    base = {
        "requirement_ref": "3.2.14",
        "requirement_text": "Do you hold ISO 27001?",
        "is_mandatory": True,
        "status": ProposalStatus.APPROVED,
        "answer_text": ENGLISH_ANSWER,
        "source_documents": ["iso-27001.pdf"],
        "citation_count": 2,
        "reviewer": "Layla",
        "reviewed_at": datetime(2026, 8, 18, 9, 30, tzinfo=UTC),
    }
    base.update(overrides)
    return ExportRow(**base)


def _docx_xml(content: bytes) -> str:
    with zipfile.ZipFile(io.BytesIO(content)) as archive:
        return archive.read("word/document.xml").decode("utf-8")


# ------------------------------------------------------------------- DOCX
def test_arabic_documents_carry_the_markers_that_make_them_right_to_left():
    """Right alignment alone is not RTL.

    Without ``w:bidi`` Word lays the paragraph out left-to-right — the glyphs
    are correct, the run order is not, and the sentence-final full stop lands
    on the wrong end.
    """
    content = build_response_docx(
        _bundle(
            Language.AR,
            _row(answer_text=ARABIC_ANSWER, requirement_text="هل لديكم شهادة الأيزو 27001؟"),
        )
    )
    xml = _docx_xml(content)

    assert "<w:bidi/>" in xml, "paragraph-level right-to-left layout"
    assert "<w:rtl/>" in xml, "run-level right-to-left characters"
    assert ARABIC_ANSWER in xml


def test_english_documents_are_not_marked_right_to_left():
    xml = _docx_xml(build_response_docx(_bundle(Language.EN, _row())))
    assert "<w:bidi/>" not in xml
    assert "<w:rtl/>" not in xml
    assert ENGLISH_ANSWER in xml


def test_the_complex_script_font_is_set_separately_from_the_latin_one():
    """Word tracks them separately; setting only the Latin face leaves Arabic
    to whatever the evaluator's machine happens to substitute."""
    content = build_response_docx(_bundle(Language.AR, _row(answer_text=ARABIC_ANSWER)))
    with zipfile.ZipFile(io.BytesIO(content)) as archive:
        styles = archive.read("word/styles.xml").decode("utf-8")
    assert 'w:cs="Arial"' in styles


def test_a_row_with_no_answer_is_absent_from_the_response_document():
    xml = _docx_xml(
        build_response_docx(
            _bundle(
                Language.EN,
                _row(),
                _row(requirement_ref="9.9", answer_text=None, status=ProposalStatus.DRAFT),
            )
        )
    )
    assert "3.2.14" in xml
    assert "9.9" not in xml


# ------------------------------------------------------------------ matrix
def test_the_arabic_matrix_opens_right_to_left_with_arabic_headers():
    content = build_compliance_matrix(_bundle(Language.AR, _row(answer_text=ARABIC_ANSWER)))
    sheet = load_workbook(io.BytesIO(content)).active

    assert sheet.sheet_view.rightToLeft is True
    assert sheet["A1"].value == "المرجع"
    # Excel's own reading order, so a Latin standard name inside an Arabic
    # sentence lays out the way a reader expects.
    assert sheet["B2"].alignment.readingOrder == 2


def test_the_english_matrix_opens_left_to_right():
    sheet = load_workbook(io.BytesIO(build_compliance_matrix(_bundle(Language.EN, _row())))).active
    assert sheet.sheet_view.rightToLeft is False
    assert sheet["A1"].value == "Reference"


def test_an_unanswered_mandatory_row_is_shaded_so_an_auditor_finds_it():
    content = build_compliance_matrix(
        _bundle(
            Language.EN,
            _row(answer_text=None, status=ProposalStatus.DRAFT),
            _row(requirement_ref="3.3", citation_count=0, source_documents=[]),
        )
    )
    sheet = load_workbook(io.BytesIO(content)).active
    missing = sheet["A2"].fill.fgColor.rgb
    uncited = sheet["A3"].fill.fgColor.rgb

    assert missing.endswith("FEE2E2"), "unanswered mandatory requirement"
    assert uncited.endswith("FEF3C7"), "answered but with no citation"
    assert missing != uncited


def test_a_timezone_aware_review_timestamp_does_not_break_the_workbook():
    """Excel has no aware datetime and openpyxl raises on one, so the naive
    conversion is load-bearing rather than cosmetic."""
    sheet = load_workbook(io.BytesIO(build_compliance_matrix(_bundle(Language.EN, _row())))).active
    assert sheet["I2"].value == datetime(2026, 8, 18, 9, 30)


# --------------------------------------------------------------------- PDF
@pytest.mark.skipif(not has_arabic_font(), reason="no Arabic-capable font installed")
def test_the_arabic_pdf_renders_and_declares_its_direction():
    content = build_pdf(_bundle(Language.AR, _row(answer_text=ARABIC_ANSWER)))
    assert content.startswith(b"%PDF-")
    assert len(content) > 1000


def test_the_english_pdf_renders():
    content = build_pdf(_bundle(Language.EN, _row()))
    assert content.startswith(b"%PDF-")


def test_the_pdf_refuses_arabic_when_no_font_can_draw_it(monkeypatch):
    """A PDF of boxes is not a degraded export — it is an unusable file that
    looks like a successful one, discovered by the procurement authority."""
    import app.exports.pdf as module
    from app.exports.pdf import ArabicFontMissingError

    monkeypatch.setattr(module, "has_arabic_font", lambda: False)
    with pytest.raises(ArabicFontMissingError):
        module.build_pdf(_bundle(Language.AR, _row(answer_text=ARABIC_ANSWER)))
