"""Declarative base, naming conventions, and shared mixins.

Everything tenant-scoped inherits from :class:`TenantMixin`, which supplies both
the ``tenant_id`` column and the composite unique constraint that makes
cross-tenant foreign keys structurally impossible (see the class docstring).
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    DateTime,
    Enum,
    ForeignKey,
    Index,
    MetaData,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID  # noqa: N811
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Deterministic constraint names. Without this, Alembic autogenerate emits
# unnamed constraints that later migrations cannot drop by name.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def pg_enum(enum_cls: type[enum.Enum], name: str, *, create_type: bool = True) -> Enum:
    """Native PostgreSQL enum column type.

    ``values_callable`` makes SQLAlchemy persist the enum *values*
    (``"bid_manager"``) rather than the Python member *names* (``"BID_MANAGER"``).
    Without it the database would hold SCREAMING_CASE that no API consumer ever
    sees, and every raw SQL query would have to know about the discrepancy.

    ``create_type=False`` is required for the second and subsequent uses of a
    shared type (``language`` appears on four tables); otherwise DDL emits
    ``CREATE TYPE`` repeatedly and the migration fails on the duplicate.
    """
    return Enum(
        enum_cls,
        name=name,
        native_enum=True,
        create_type=create_type,
        values_callable=lambda e: [member.value for member in e],
    )


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {dict[str, Any]: JSONB}

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        pk = getattr(self, "id", None)
        return f"<{type(self).__name__} id={pk}>"


class UUIDPrimaryKeyMixin:
    """UUID primary keys, generated by the database.

    Generated server-side via ``gen_random_uuid()`` (pgcrypto, built into
    PostgreSQL 13+) so that rows created by raw SQL, migrations, or bulk loaders
    get valid keys too — not only rows created through the ORM.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Creation/update timestamps maintained by the database clock.

    ``server_default``/``onupdate`` are used rather than Python defaults so the
    values stay correct and monotonic across API pods, Celery workers, and
    manual SQL — all of which write these tables.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Soft deletion.

    Tender responses are commercial records: a customer deleting a workspace
    must not destroy the audit trail that proves which sources a submitted
    answer was grounded in. Rows are tombstoned and filtered by the repository
    layer; hard deletion happens only through the retention job.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class TenantMixin:
    """Tenant ownership column plus the composite key that enforces isolation.

    Two mechanisms work together, and the second is the one that matters:

    1. ``tenant_id`` is the discriminator every Row-Level Security policy reads
       (``USING (tenant_id = current_setting('app.tenant_id')::uuid)``).

    2. ``UNIQUE (tenant_id, id)`` is redundant for uniqueness — ``id`` is
       already the primary key — but it gives child tables a target for a
       *composite* foreign key ``(tenant_id, parent_id) -> (tenant_id, id)``.
       That makes "workspace in tenant A referencing a document in tenant B" a
       constraint violation at the database level, not merely a bug the
       application is trusted to avoid.

    RLS is defence in depth; the composite FK is the structural guarantee. Both
    are enabled in the Alembic migration, since neither is expressible as a
    column default.
    """

    @declared_attr
    def tenant_id(cls) -> Mapped[uuid.UUID]:  # noqa: N805
        return mapped_column(
            PgUUID(as_uuid=True),
            ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )

    #: Subclasses add their own constraints here instead of overriding
    #: ``__table_args__``, which would silently drop the tenant guarantees below.
    __extra_table_args__: tuple[Any, ...] = ()

    @declared_attr.directive
    def __table_args__(cls) -> tuple[Any, ...]:  # noqa: N805
        return (
            UniqueConstraint("tenant_id", "id", name=f"uq_{cls.__tablename__}_tenant_id_id"),
            Index(f"ix_{cls.__tablename__}_tenant_created", "tenant_id", "created_at"),
            *cls.__extra_table_args__,
        )
