"""initial schema

Revision ID: a78e778fe2d2
Revises:
Create Date: 2026-08-18 13:32:05.598386
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a78e778fe2d2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Native enum types created by this migration. Alembic emits the CREATE TYPE
#: implicitly alongside the columns but never the matching DROP.
ENUM_TYPES = (
    "tenant_plan",
    "language",
    "user_role",
    "workspace_status",
    "document_role",
    "document_status",
    "parse_strategy",
    "grounding_verdict",
    "proposal_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("trial", "starter", "professional", "enterprise", name="tenant_plan"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "default_locale",
            sa.Enum("ar", "en", "mixed", "unknown", name="language"),
            nullable=False,
        ),
        sa.Column("seats_limit", sa.Integer(), nullable=False),
        sa.Column(
            "storage_quota_bytes",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            nullable=False,
        ),
        sa.Column("monthly_generation_limit", sa.Integer(), nullable=False),
        sa.Column("sso_issuer_url", sa.String(length=512), nullable=True),
        sa.Column("branding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("seats_limit > 0", name=op.f("ck_tenants_seats_limit_positive")),
        sa.CheckConstraint(
            "storage_quota_bytes >= 0", name=op.f("ck_tenants_storage_quota_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(op.f("ix_tenants_created_at"), "tenants", ["created_at"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("external_subject_id", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("owner", "bid_manager", "sme", "viewer", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "locale", sa.Enum("ar", "en", "mixed", "unknown", name="language"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_users_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_id_email"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_users_tenant_id_id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("ix_users_external_subject_id"), "users", ["external_subject_id"], unique=False
    )
    op.create_index("ix_users_tenant_created", "users", ["tenant_id", "created_at"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "analyzing",
                "generating",
                "in_review",
                "approved",
                "submitted",
                "archived",
                "lost",
                name="workspace_status",
            ),
            nullable=False,
        ),
        sa.Column("tender_reference", sa.String(length=128), nullable=True),
        sa.Column("issuing_authority", sa.String(length=255), nullable=True),
        sa.Column("submission_deadline", sa.Date(), nullable=True),
        sa.Column(
            "estimated_value",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            nullable=True,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "response_language",
            sa.Enum("ar", "en", "mixed", "unknown", name="language"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("grounding_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requirements_total", sa.Integer(), nullable=False),
        sa.Column("requirements_approved", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_workspaces_currency_iso4217"),
        ),
        sa.CheckConstraint(
            "requirements_approved >= 0 AND requirements_approved <= requirements_total",
            name=op.f("ck_workspaces_approved_within_total"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "owner_id"],
            ["users.tenant_id", "users.id"],
            name="fk_workspaces_owner_same_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_workspaces_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_workspaces_tenant_id_id"),
    )
    op.create_index(
        "ix_workspaces_active_deadline",
        "workspaces",
        ["tenant_id", "submission_deadline"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_workspaces_created_at"), "workspaces", ["created_at"], unique=False)
    op.create_index(op.f("ix_workspaces_owner_id"), "workspaces", ["owner_id"], unique=False)
    op.create_index(op.f("ix_workspaces_status"), "workspaces", ["status"], unique=False)
    op.create_index(
        "ix_workspaces_tenant_created", "workspaces", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_workspaces_tenant_id"), "workspaces", ["tenant_id"], unique=False)
    op.create_index(
        "ix_workspaces_tenant_status", "workspaces", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_workspaces_tender_reference"), "workspaces", ["tender_reference"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "tender", "knowledge_base", "past_proposal", "attachment", name="document_role"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "uploaded",
                "parsing",
                "chunking",
                "embedding",
                "ready",
                "failed",
                "quarantined",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "parse_strategy",
            sa.Enum("fast", "hi_res", "ocr_only", "native_tabular", name="parse_strategy"),
            nullable=True,
        ),
        sa.Column(
            "language", sa.Enum("ar", "en", "mixed", "unknown", name="language"), nullable=False
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("text_extraction_ratio", sa.Float(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("doc_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status <> 'failed') OR (failure_reason IS NOT NULL)",
            name=op.f("ck_documents_failed_requires_reason"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_documents_size_positive")),
        sa.CheckConstraint(
            "text_extraction_ratio IS NULL OR "
            "(text_extraction_ratio >= 0 AND text_extraction_ratio <= 1)",
            name=op.f("ck_documents_extraction_ratio_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "workspace_id"],
            ["workspaces.tenant_id", "workspaces.id"],
            name="fk_documents_workspace_same_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_documents_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("tenant_id", "content_sha256", name="uq_documents_tenant_id_sha256"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_documents_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_documents_content_sha256"), "documents", ["content_sha256"], unique=False
    )
    op.create_index(op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False)
    op.create_index(op.f("ix_documents_role"), "documents", ["role"], unique=False)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(
        "ix_documents_tenant_created", "documents", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_index(
        "ix_documents_tenant_status", "documents", ["tenant_id", "status"], unique=False
    )
    op.create_index(op.f("ix_documents_workspace_id"), "documents", ["workspace_id"], unique=False)
    op.create_index(
        "ix_documents_workspace_role", "documents", ["workspace_id", "role"], unique=False
    )
    op.create_table(
        "generated_proposals",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("requirement_ref", sa.String(length=128), nullable=False),
        sa.Column("requirement_text", sa.Text(), nullable=False),
        sa.Column("section_path", sa.String(length=512), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("edited_text", sa.Text(), nullable=True),
        sa.Column(
            "language", sa.Enum("ar", "en", "mixed", "unknown", name="language"), nullable=False
        ),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retrieved_chunk_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "grounding_verdict",
            sa.Enum(
                "verified", "partial", "unverified", "not_applicable", name="grounding_verdict"
            ),
            nullable=False,
        ),
        sa.Column("citation_coverage", sa.Float(), nullable=True),
        sa.Column("top_retrieval_score", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("abstention_reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "abstained",
                "pending_review",
                "needs_sme",
                "rejected",
                "approved",
                "exported",
                name="proposal_status",
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("assigned_sme_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("previous_version_id", sa.UUID(), nullable=True),
        sa.Column("model_id", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("generation_ms", sa.Integer(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'abstained' OR (abstention_reason IS NOT NULL AND answer_text IS NULL)",
            name=op.f("ck_generated_proposals_abstained_requires_reason"),
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)",
            name=op.f("ck_generated_proposals_approved_requires_reviewer"),
        ),
        sa.CheckConstraint(
            "citation_coverage IS NULL OR (citation_coverage >= 0 AND citation_coverage <= 1)",
            name=op.f("ck_generated_proposals_coverage_in_range"),
        ),
        sa.CheckConstraint(
            "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)",
            name=op.f("ck_generated_proposals_confidence_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reviewed_by_id"],
            ["users.tenant_id", "users.id"],
            name="fk_proposals_reviewer_same_tenant",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "workspace_id"],
            ["workspaces.tenant_id", "workspaces.id"],
            name="fk_proposals_workspace_same_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_generated_proposals_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_proposals")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_generated_proposals_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_generated_proposals_created_at"),
        "generated_proposals",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_proposals_grounding_verdict"),
        "generated_proposals",
        ["grounding_verdict"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_proposals_requirement_ref"),
        "generated_proposals",
        ["requirement_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_proposals_status"), "generated_proposals", ["status"], unique=False
    )
    op.create_index(
        "ix_generated_proposals_tenant_created",
        "generated_proposals",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_proposals_tenant_id"), "generated_proposals", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_generated_proposals_workspace_id"),
        "generated_proposals",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_proposals_citations_gin",
        "generated_proposals",
        ["citations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_proposals_workspace_status",
        "generated_proposals",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_proposals_current_requirement",
        "generated_proposals",
        ["workspace_id", "requirement_ref"],
        unique=True,
        postgresql_where=sa.text("is_current AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_proposals_current_requirement",
        table_name="generated_proposals",
        postgresql_where=sa.text("is_current AND deleted_at IS NULL"),
    )
    op.drop_index("ix_proposals_workspace_status", table_name="generated_proposals")
    op.drop_index(
        "ix_proposals_citations_gin", table_name="generated_proposals", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_generated_proposals_workspace_id"), table_name="generated_proposals")
    op.drop_index(op.f("ix_generated_proposals_tenant_id"), table_name="generated_proposals")
    op.drop_index("ix_generated_proposals_tenant_created", table_name="generated_proposals")
    op.drop_index(op.f("ix_generated_proposals_status"), table_name="generated_proposals")
    op.drop_index(op.f("ix_generated_proposals_requirement_ref"), table_name="generated_proposals")
    op.drop_index(
        op.f("ix_generated_proposals_grounding_verdict"), table_name="generated_proposals"
    )
    op.drop_index(op.f("ix_generated_proposals_created_at"), table_name="generated_proposals")
    op.drop_table("generated_proposals")
    op.drop_index("ix_documents_workspace_role", table_name="documents")
    op.drop_index(op.f("ix_documents_workspace_id"), table_name="documents")
    op.drop_index("ix_documents_tenant_status", table_name="documents")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index("ix_documents_tenant_created", table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_role"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_sha256"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_workspaces_tender_reference"), table_name="workspaces")
    op.drop_index("ix_workspaces_tenant_status", table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_tenant_id"), table_name="workspaces")
    op.drop_index("ix_workspaces_tenant_created", table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_status"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_owner_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_created_at"), table_name="workspaces")
    op.drop_index(
        "ix_workspaces_active_deadline",
        table_name="workspaces",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index("ix_users_tenant_created", table_name="users")
    op.drop_index(op.f("ix_users_external_subject_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_created_at"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###

    # Autogenerate drops the tables but leaves the native enum TYPES behind, so
    # a downgrade followed by a fresh upgrade fails with
    # "type tenant_plan already exists". That turns a rollback into a dead end:
    # you can go back, but you cannot go forward again — precisely when you are
    # least able to afford it. Dropping them explicitly keeps the migration
    # genuinely reversible.
    for enum_name in ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
